# Generated by Django 5.2.6 on 2025-09-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
